blank_issues_enabled: true
contact_links:
  - name: Killerx Support
    url: https://t.me/CodeDev_Support
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://github.com/Randi356/KillerX-Music
    about: Basic documentation for setting up.
